import { Creation } from '@/types';

export const CREATIONS: Creation[] = [
  {
    id: 'aurelia',
    title: 'Aurelia',
    slug: 'aurelia',
    year: 2021,
    medium: 'Genesis Heat-Set Oils on German Soft Vinyl, Micro-Rooted Angora Mohair',
    technique: 'Single-strand micro-rooting (42G), 28 translucent subdermal glaze layers, natural lip hydration sheen',
    weight: '2.7 kg / 5.95 lbs',
    length: '50.8 cm / 20.0 in',
    eyeDetails: 'Sleeping eyelids with micro-veining and individually seeded blonde lashes',
    hairDetails: 'Ultra-fine natural blonde Angora mohair rooted strand by strand with crown spiral',
    coverImage: '/assets/baby3.jpg',
    images: ['/assets/baby3.jpg', '/assets/baby3_macro.jpg'],
    detailImages: [
      {
        url: '/assets/baby3_macro.jpg',
        title: {
          en: 'Micro-Rooted Lashes & Epidermal Sheen',
          es: 'Pestañas Micro-Enraizadas y Brillo Epidérmico',
        },
        caption: {
          en: 'Single-strand micro-rooting along the lash line, capturing natural newborn moisture and translucent skin tones.',
          es: 'Enraizado individual a lo largo de la línea de pestañas, capturando la humedad natural y tonos translúcidos.',
        },
        alt: 'Close-up of Aurelia eyelashes and lip texture',
      },
    ],
    status: 'Private Collection',
    featured: true,
    hasCertificate: true,
    series: 'Reborn Hyperrealism',
    description: {
      en: 'A profound study of newborn stillness. Aurelia rests in deep slumber, cradled in tactile textures of raw fleece and organic fiber.',
      es: 'Un estudio profundo sobre la quietud del recién nacido. Aurelia descansa en un sueño profundo, acunada en vellón y fibras orgánicas.',
    },
    story: {
      en: 'Aurelia was conceived as an exploration of fragility and absolute peace. Rather than dramatizing movement, Melissa focused on the quietest micro-moments: the subtle curl of infant lips in dream state, the faint peach fuzz over the brow bone, and the delicate warmth radiating from soft cheeks.',
      es: 'Aurelia fue concebida como una exploración de la fragilidad y la paz absoluta. En lugar de dramatizar el movimiento, Melissa se enfocó en los micro-momentos más sutiles: la curvatura tenue de los labios, el vello suave sobre las cejas y la calidez que irradian sus mejillas.',
    },
    craftNotes: {
      en: 'Crafted through 28 distinct heat-cured oil washes to achieve realistic skin mottling and depth. Hair was implanted strand by strand using 42-gauge ultra-fine felting needles, sealed internally with a permanent flexible waterproof compound to allow gentle styling.',
      es: 'Elaborada mediante 28 veladuras al óleo curadas al horno para lograr el veteado y profundidad de la piel. El cabello fue implantado hebra por hebra con agujas de 42 gauges y sellado internamente con compuesto impermeable y flexible.',
    },
  },
  {
    id: 'joseph-julien',
    title: 'Julien',
    slug: 'julien',
    year: 2021,
    dateCreated: '2021-07-23',
    sculptorKit: 'Joseph (3-Month Infant)',
    originalSculptor: 'Bountiful Baby Studio',
    medium: 'Genesis Heat-Set Artist Oils, Weighted Cotton Body, Hand-Blown German Crystal Eyes, Mohair',
    technique: 'Multi-layer subdermal mottle, 32 oven-cured translucent washes, micro-veining, tipped nails, cloth body with weighted limb joints',
    weight: '3.5 kg / 7.7 lbs',
    length: '58.42 cm / 23.0 in',
    eyeDetails: 'German paperweight crystal glass eyes in deep steel blue with lifelike depth',
    hairDetails: 'Soft medium-brown micro-rooted mohair with natural newborn temporal swirl',
    coverImage: '/assets/baby1.jpg',
    images: ['/assets/baby1.jpg', '/assets/baby1_portrait.jpg', '/assets/baby1_certificate.jpg'],
    detailImages: [
      {
        url: '/assets/baby1_certificate.jpg',
        title: {
          en: 'Authentic Certificate of Authenticity',
          es: 'Certificado de Autenticidad Original',
        },
        caption: {
          en: 'Issued July 23, 2021, documenting birth weight (3.5 kg), length (58.42 cm), signed and sealed by artist Melissa Rendon.',
          es: 'Emitido el 23 de julio de 2021, documentando peso (3.5 kg), longitud (58.42 cm), firmado y sellado por la artista Melissa Rendon.',
        },
        alt: 'Baby Maker Petit Certificate of Authenticity signed by Melissa Rendon',
      },
      {
        url: '/assets/baby1_portrait.jpg',
        title: {
          en: 'Portrait Study: Cap & Linen Shirt',
          es: 'Estudio de Retrato: Boina y Camisa de Lino',
        },
        caption: {
          en: 'Heirloom styling emphasizing gentle infant curiosity and three-month developmental fullness.',
          es: 'Estilismo patrimonial que enfatiza la curiosidad y la contextura natural de los tres meses de vida.',
        },
        alt: 'Julien wearing newsboy cap and linen shirt',
      },
    ],
    status: 'Private Collection',
    featured: true,
    hasCertificate: true,
    certificateDate: '23/07/2021',
    series: 'Reborn Hyperrealism',
    description: {
      en: 'A flagship creation documenting the milestone transition into larger infant proportions, accompanied by its authentic registered Certificate of Authenticity.',
      es: 'Una creación emblemática que documenta la transición hacia proporciones infantiles mayores, acompañada de su Certificado de Autenticidad oficial registrado.',
    },
    story: {
      en: 'Sculpted from the 3-month Joseph kit, Julien represents a pivotal piece in the atelier. At 3.5 kilograms and over 58 centimeters in length, holding Julien mirrors the physical gravitational balance of a real three-month infant. Dressed in tailored newsboy cap and collared linen with bow tie, he carries timeless dignity.',
      es: 'Esculpido a partir del kit Joseph de 3 meses, Julien representa una obra clave en el atelier. Con 3.5 kg y más de 58 cm, sostener a Julien reproduce el equilibrio gravitacional exacto de un bebé real de tres meses. Con su boina sastre y camisa de lino con pajarita, transmite una dignidad atemporal.',
    },
    craftNotes: {
      en: 'Features custom joint articulation balanced with fine glass micro-beads and virgin polyfill. Each fingernail is individually tipped with micro-lunate crescent paint and finished with a satin-matte protective seal.',
      es: 'Cuenta con articulación personalizada equilibrada con microesferas de vidrio y fibra virgen. Cada uña está rematada con media luna natural y sellada con acabado satinado mate protector.',
    },
  },
  {
    id: 'saskia',
    title: 'Saskia',
    slug: 'saskia',
    year: 2020,
    dateCreated: '2020-07-22',
    sculptorKit: 'Saskia',
    originalSculptor: 'Bonnie Brown',
    medium: 'German Soft Vinyl, Hand-Blown Acrylic/Glass Eyes, Hand-Rooted Mohair, Hand-Knit Wool',
    technique: 'Complex facial muscle shading, delicate capillary mapping, hand-knitted pastel cardigan',
    weight: '2.6 kg / 5.7 lbs',
    length: '55.8 cm / 22.0 in',
    eyeDetails: 'Deep warm hazel-amber glass eyes with reflective corneal contouring',
    hairDetails: 'Fine honey-blonde rooted mohair parted naturally around the temples',
    coverImage: '/assets/baby4_clean.png',
    images: ['/assets/baby4_clean.png', '/assets/baby4.png'],
    detailImages: [
      {
        url: '/assets/baby4.png',
        title: {
          en: 'Historical Atelier Record (July 2020)',
          es: 'Registro Histórico del Atelier (Julio 2020)',
        },
        caption: {
          en: 'Archival Instagram publication from July 22, 2020, marking one of the founding pieces of the Baby Maker Petit practice.',
          es: 'Publicación de archivo de Instagram del 22 de julio de 2020, que marca una de las obras fundacionales de Baby Maker Petit.',
        },
        alt: 'Original archival publication of Saskia',
      },
    ],
    status: 'Private Collection',
    featured: true,
    hasCertificate: true,
    series: 'Reborn Hyperrealism',
    description: {
      en: 'An iconic, wide-eyed creation capturing an open-mouthed expression of innocent wonder, foundational to the early history of the atelier.',
      es: 'Una creación icónica de ojos abiertos que captura una expresión de asombro inocente, fundamental en la historia temprana del taller.',
    },
    story: {
      en: 'Saskia was sculpted from Bonnie Brown’s celebrated sculpt and brought to life in July 2020. Her expressive open hands, lifted slightly in anticipation, and curious parted lips make her feel vibrantly alive. She served as an early benchmark for Melissa’s mastery of facial expression.',
      es: 'Saskia fue esculpida a partir del célebre molde de Bonnie Brown y finalizada en julio de 2020. Sus manitas expresivas alzadas y sus labios entreabiertos le otorgan una viveza extraordinaria. Fue una referencia temprana en el dominio de las expresiones faciales por parte de Melissa.',
    },
    craftNotes: {
      en: 'The facial tone was built through dozens of mottled micro-layers to emulate the flush of a newborn waking up. Paired with hand-knit soft pink cardigan and custom text-print trousers.',
      es: 'El tono facial fue construido mediante decenas de microcapas de veteado para emular el rubor de un bebé al despertar. Acompañada de cárdigan rosa tejido a mano y pantalón estampado.',
    },
  },
  {
    id: 'clara',
    title: 'Clara',
    slug: 'clara',
    year: 2021,
    medium: 'Large Toddler Soft Vinyl, Dual-Tone Auburn Mohair, Sculpted Oral Anatomy, Wood-Button Cardigan',
    technique: 'Sculpted teeth and oral depth, custom facial freckles, dual-tone micro-rooting with hair parts',
    weight: '3.8 kg / 8.4 lbs',
    length: '66.0 cm / 26.0 in',
    eyeDetails: 'Laughing, squinted dark eyes with fine crow-line skin folds',
    hairDetails: 'Long auburn and copper mohair micro-rooted along distinct central parting into twin pigtails',
    coverImage: '/assets/baby5.jpg',
    images: ['/assets/baby5.jpg', '/assets/baby5_smile.jpg', '/assets/baby5_hair.jpg'],
    detailImages: [
      {
        url: '/assets/baby5_smile.jpg',
        title: {
          en: 'Oral Anatomy & Nascent Teeth',
          es: 'Anatomía Oral y Primeros Dientes',
        },
        caption: {
          en: 'Sculpted lower milk teeth, tongue texture, and sun-kissed epidermal freckles capturing radiant childhood laughter.',
          es: 'Dientes de leche inferiores esculpidos, textura lingual y pecas epidérmicas que capturan una risa infantil radiante.',
        },
        alt: 'Close-up of Clara laughing mouth and teeth',
      },
      {
        url: '/assets/baby5_hair.jpg',
        title: {
          en: 'Micro-Rooted Central Crown Parting',
          es: 'Enraizado Microscópico de la Raya Central',
        },
        caption: {
          en: 'Directional rooting into the scalp vinyl to create a seamless, natural parting line without visible puncture marks.',
          es: 'Enraizado direccional en el vinilo para crear una línea de partición natural sin marcas de punción visibles.',
        },
        alt: 'Micro-rooted hair parting on Clara',
      },
    ],
    status: 'Private Collection',
    featured: true,
    hasCertificate: true,
    series: 'Reborn Hyperrealism',
    description: {
      en: 'A joyous departure into toddler sculpture. Clara captures radiant laughter with nascent teeth, sun-kissed freckles, and auburn pigtails.',
      es: 'Una incursión luminosa en la escultura de niños pequeños. Clara captura una risa alegre con dientes incipientes, pecas y coletas cobrizas.',
    },
    story: {
      en: 'Most reborn art gravitates toward sleeping or passive infants. Clara intentionally challenges this convention with unrestrained joy. Melissa sculpted the oral cavity to show two emerging bottom teeth, blushing tongue, and fine laugh lines crinkling her eyes.',
      es: 'La mayor parte del arte reborn se enfoca en bebés durmiendo o pasivos. Clara desafía esta convención con una alegría desbordante. Melissa esculpió la cavidad bucal mostrando dos dientecitos inferiores, lengua sonrosada y líneas de risa alrededor de los ojos.',
    },
    craftNotes: {
      en: 'Micro-rooting long auburn mohair took over 60 hours of continuous atelier work. Each hair was inserted at a sharp angle to flow organically down the back into pigtails with invisible scalp pores.',
      es: 'El microenraizado del cabello castaño cobrizo requirió más de 60 horas de trabajo continuo. Cada cabello fue insertado en ángulo para caer orgánicamente hacia las coletas con poros imperceptibles.',
    },
  },
  {
    id: 'vesper',
    title: 'Vesper',
    slug: 'vesper',
    year: 2022,
    medium: 'German Soft Vinyl, Fine Brunette Mohair, Hand-Tailored Floral Bonnet & Vintage Cotton Gown',
    technique: 'Classical portrait palette, delicate eyelid capillaries, historical lace integration',
    weight: '2.5 kg / 5.5 lbs',
    length: '49.5 cm / 19.5 in',
    eyeDetails: 'Closed peaceful eyes with soft dark lashes and violet eyelid undertones',
    hairDetails: 'Short dark chocolate mohair with soft forehead curls under heirloom bonnet',
    coverImage: '/assets/baby7.png',
    images: ['/assets/baby7.png'],
    status: 'Atelier Archive',
    featured: false,
    hasCertificate: true,
    series: 'Reborn Hyperrealism',
    description: {
      en: 'A classical portrait piece reminiscent of Flemish oil paintings, framed by custom floral headwear and delicate lace ruffles.',
      es: 'Una obra de retrato clásico que evoca la pintura flamenca, enmarcada por un gorrito floral sastre y delicados encajes.',
    },
    story: {
      en: 'Vesper bridges the gap between hyperrealistic infant sculpture and historical portrait art. Dressed in soft meadow-yellow and blue floral cotton, her peaceful repose evokes the timeless serenity of old masters’ canvases.',
      es: 'Vesper tiende un puente entre la escultura hiperrealista y el retrato histórico. Vestida en algodón floral en tonos pradera y azul, su sosiego evoca la serenidad de los grandes lienzos clásicos.',
    },
    craftNotes: {
      en: 'Painted with special attention to cool eyelid undertones and delicate brow feathering. The textile ensemble was individually tailored to complement the warm ivory tones of her complexion.',
      es: 'Pintada con especial atención a los matices fríos en los párpados y plumaje delicado en las cejas. Las prendas fueron confeccionadas a medida para armonizar con su tez marfil.',
    },
  },
  {
    id: 'noa',
    title: 'Noa',
    slug: 'noa',
    year: 2021,
    medium: 'European Soft Vinyl, Hand-Blown Glass Eyes, Light Mohair, Custom Magnetized Pacifier',
    technique: 'Magnetic oral assembly, subtle temple veining, ear cartilage multi-layer shading',
    weight: '2.4 kg / 5.3 lbs',
    length: '48.0 cm / 18.9 in',
    eyeDetails: 'Hand-blown glass eyes in sea-glass green with natural light refractive depth',
    hairDetails: 'Fine wispy strawberry-blonde hair with delicate newborn temple swirling',
    coverImage: '/assets/baby6.png',
    images: ['/assets/baby6.png'],
    status: 'Private Collection',
    featured: false,
    hasCertificate: true,
    series: 'Reborn Hyperrealism',
    description: {
      en: 'An intimate portrait of calm contemplation, featuring crystalline glass eyes, subtle temple veins, and ear cartilage translucency.',
      es: 'Un retrato íntimo de contemplación serena, con ojos de cristal verde agua, finas venas en la sien y cartílago auricular translúcido.',
    },
    story: {
      en: 'Noa showcases Melissa’s nuanced approach to the gaze. Her eyes possess an arresting clarity that follows the viewer across the gallery space. Internal earth magnets allow the pacifier to be placed or removed with a tactile snap.',
      es: 'Noa resalta el enfoque minucioso de Melissa respecto a la mirada. Sus ojos poseen una claridad magnética que parece acompañar al espectador. Imanes internos de neodimio permiten colocar el chupete con un suave chasquido táctil.',
    },
    craftNotes: {
      en: 'Ear cartilage was shaded across four distinct tonal steps to mimic the optical scattering of light through thin human tissue.',
      es: 'El cartílago de las orejas fue sombreado en cuatro pasos tonales para imitar la dispersión de la luz a través del tejido vivo.',
    },
  },
  {
    id: 'elio',
    title: 'Elio',
    slug: 'elio',
    year: 2021,
    medium: 'Soft Vinyl, Knit Navy Snood, Articulated Torso, Glass Micro-Bead Weighting',
    technique: 'Macro plantar detailing, sole creasing, capillary redness, tipped micro-lunula toenails',
    weight: '2.8 kg / 6.2 lbs',
    length: '52.0 cm / 20.5 in',
    eyeDetails: 'Deep cobalt blue glass eyes nestled beneath knitted hood',
    hairDetails: 'Soft downy strawberry-blonde hair peeking under navy wool snood',
    coverImage: '/assets/baby2.jpg',
    images: ['/assets/baby2.jpg', '/assets/baby2_feet.jpg'],
    detailImages: [
      {
        url: '/assets/baby2_feet.jpg',
        title: {
          en: 'Plantar Anatomy & Crease Realism',
          es: 'Anatomía Plantar y Pliegues Reales',
        },
        caption: {
          en: 'Extreme close-up of sole creases, sub-surface capillary redness, and translucent toenails tipped with natural lunula.',
          es: 'Primer plano de pliegues en la planta del pie, rojeces capilares subepidérmicas y uñas translúcidas con lúnula natural.',
        },
        alt: 'Detailed hyperrealistic feet and toes on Elio',
      },
    ],
    status: 'Atelier Study',
    featured: false,
    hasCertificate: true,
    series: 'Atelier Studies',
    description: {
      en: 'An anatomical tour-de-force highlighting the often-overlooked realism of infant feet—wrinkled soles, red undertones, and micro-nails.',
      es: 'Una clase magistral de anatomía que destaca el realismo de los pies de un bebé: plantas arrugadas, tonos rojizos y micro-uñas.',
    },
    story: {
      en: 'To make craftsmanship unmistakable from mass production, Melissa dedicates equal rigor to the extremities as to the face. Elio presents an unfiltered study of infant plantar anatomy: the delicate folds of soft heels and the tiny crescent moon of each nail.',
      es: 'Para diferenciar el arte de la producción en masa, Melissa dedica el mismo rigor a las extremidades que al rostro. Elio presenta un estudio sin filtros de la anatomía plantar: los pliegues del talón y la pequeña luna creciente de cada uña.',
    },
    craftNotes: {
      en: 'Soles painted with specialized mottled blushing, sealed with custom textured matte medium to provide an authentic velvety skin feel to the touch.',
      es: 'Las plantas de los pies se pintaron con motas especializadas y se sellaron con medio mate texturizado para brindar un tacto aterciopelado idéntico a la piel real.',
    },
  },
  {
    id: 'atelier-study-genesis',
    title: 'Atelier Study No. 01: Subdermal Layers',
    slug: 'atelier-study-genesis',
    year: 2022,
    medium: 'Raw German Soft Vinyl Blank, Genesis Artist Colors, Oven-Cured Mineral Mediums',
    technique: '25+ layers of heat-cured mottling, subdermal blue veins, blushing, nail bed prep prior to eye insertion',
    coverImage: '/assets/baby8.png',
    images: ['/assets/baby8.png', '/assets/baby8_head.jpg', '/assets/baby8_hands.jpg'],
    detailImages: [
      {
        url: '/assets/baby8_head.jpg',
        title: {
          en: 'Subdermal Mottling on Raw Vinyl',
          es: 'Veteado Subepidérmico en Vinilo Virgen',
        },
        caption: {
          en: 'Macro view of the cranial shell showing micro-veins and mottled layers before eye insertion and hair rooting.',
          es: 'Vista macro de la cabeza que muestra microvenas y capas de veteado antes de insertar los ojos y enraizar el cabello.',
        },
        alt: 'Raw painted vinyl head showing mottling',
      },
      {
        url: '/assets/baby8_hands.jpg',
        title: {
          en: 'Hand & Limb Detailing Before Assembly',
          es: 'Detalle de Manos y Extremidades Pre-Ensamblaje',
        },
        caption: {
          en: 'Individual fingers showing knuckle blushing, vascular tones, and pristine nail tipping ready for mounting rings.',
          es: 'Dedos individuales con rubor en nudillos, tonos vasculares y uñas listas para el montaje.',
        },
        alt: 'Painted vinyl hands with detailed veins and nails',
      },
    ],
    status: 'Atelier Study',
    featured: false,
    hasCertificate: false,
    series: 'Atelier Studies',
    description: {
      en: 'The unmasked reality of the craft: raw sculpted vinyl undergoing dozens of translucent oil washes to synthesize optical skin depth.',
      es: 'La realidad sin filtros del oficio: vinilo virgen sometido a decenas de veladuras al óleo para sintetizar la profundidad óptica de la piel.',
    },
    story: {
      en: 'This archival study preserves the intermediate stage of sculpture. Before glass eyes are aligned and before thousands of mohair follicles are introduced, the vinyl shell already breathes through twenty-five separate heat-cured glaze layers that recreate capillary blood flow beneath the surface.',
      es: 'Este estudio de archivo preserva la etapa intermedia de la escultura. Antes de alinear los ojos de cristal y de implantar miles de cabellos de mohair, la pieza de vinilo ya cobra vida gracias a veinticinco veladuras horneadas que recrean el flujo capilar.',
    },
    craftNotes: {
      en: 'Each wash is cured at precisely 130°C in a specialized convection oven. Flange rings at the neck and limbs remain intact until final weighting calibration.',
      es: 'Cada veladura se hornea a 130°C exactos en un horno de convección especializado. Los anillos de sujeción en cuello y extremidades se mantienen intactos hasta el calibrado de peso.',
    },
  },
  {
    id: 'atelier-assembly-bench',
    title: 'Atelier Assembly: The Workbench',
    slug: 'atelier-assembly-bench',
    year: 2021,
    medium: 'Weighted Cloth Body, Cable-Tension Joints, Studio Brushes & Natural Fiber Basket',
    technique: 'Internal gravitational distribution, neck tensioning, micro-bead weighting',
    coverImage: '/assets/baby3_process.jpg',
    images: ['/assets/baby3_process.jpg'],
    status: 'Atelier Study',
    featured: false,
    hasCertificate: false,
    series: 'Atelier Studies',
    description: {
      en: 'A candid glimpse into Melissa’s atelier workbench during anatomical assembly, balance calibration, and joint tensioning.',
      es: 'Un vistazo sincero al banco de trabajo del taller de Melissa durante el ensamblaje anatómico, balance de peso y tensión de articulaciones.',
    },
    story: {
      en: 'Captured in the atelier surrounded by fine bristle brushes, glass jars, and another sculpted head waiting in the background. The assembly phase connects the painted vinyl extremities to a custom weighted body, ensuring the sculpture slumps naturally into the arms of the holder.',
      es: 'Fotografiado en el taller rodeado de pinceles finos, frascos de cristal y otra cabecita esperando en segundo plano. La fase de ensamblaje une las extremidades de vinilo a un cuerpo con peso, logrando que la escultura descanse con naturalidad al ser sostenida.',
    },
    craftNotes: {
      en: 'Tension ties are concealed within soft Ultrasuede and flannel casing. The neck joint is calibrated with slight looseness to require supporting the head as with a real newborn.',
      es: 'Las bridas de tensión quedan ocultas dentro de fundas de franela y ultrasuede. La articulación del cuello se calibra con soltura sutil para requerir sostén de cabeza como un recién nacido real.',
    },
  },
];
